cardThumbAlignment: end
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-12-02T14:53:19+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: 59a07c53-8202-4271-9dea-a6cdc925adf6
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-12-02T14:53:19+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: a93639bb-3a67-483b-a4e8-354ee23b8c4d
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-12-02T14:53:19+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: 2d771e01-c938-4e62-a607-04ce49e47f46
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-12-02T14:53:19+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: 8fb3b517-752d-48c4-8638-cad16e0d0944
        userCondition: null
        width: 100
    name: Content
    uid: a75f878d-f832-4c19-b857-958f58dabaad
    userCondition: null
