altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1973666c-820b-47f0-8d8b-13d4cf7efb6e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-01T22:33:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4909ddd4-c981-4cc7-ba7b-4ac13dbe28f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0dc2c15-cba3-4a5b-9f2f-e83b86ab01d6
        userCondition: null
fs: uploadsFs
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
