dateModified: 1764688742
email:
  fromEmail: uhakruthi1@gmail.com
  fromName: 'Recipe Book'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploadsFs:
    hasUrls: true
    name: 'Uploads Filesystem'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads
meta:
  __names__:
    3b72cbae-ce32-4fad-8ad7-37869fbe12e7: ingredients # ingredients
    34b082af-a3d9-44d2-9799-bf7d3acd57c3: Bio # Bio
    60ed0367-b2c6-4d4d-a156-213952b23706: 'Recipe Book' # Recipe Book
    070fd4f1-0816-460d-8a56-8ad39aae9a86: 'Meal Category' # Meal Category
    42072a54-f997-4f7f-8edc-ccb3efaba298: 'Public Schema' # Public Schema
    961147a0-5068-4af3-8c76-1523d461e279: 'Cook Time' # Cook Time
    b9c813dc-6f30-4645-b9a0-b233189d276c: Recipe # Recipe
    bd4050ed-c4eb-4f84-b48e-1bdd4388712d: Description # Description
    c2e9e108-babb-4c82-8ebb-38b86ba8e2e6: 'Recipe Book' # Recipe Book
    c9a288c4-e6d5-4bb0-baf1-44edd43bc5c7: Uploads # Uploads
    c88a916c-f8fb-4353-9fc9-2b0a6d168e4b: Recipes # Recipes
    dcc420d3-b3ff-4a4e-9567-e15852b79a16: steps # steps
    e1963a35-9ce0-4742-b4a0-d2ef406311a7: 'Recipe Image' # Recipe Image
    ffffa147-df16-4e7d-91e7-5f59365adffd: Difficulty # Difficulty
plugins:
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
system:
  edition: solo
  live: true
  name: 'Recipe Book'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
