defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b9c813dc-6f30-4645-b9a0-b233189d276c # Recipe
handle: recipes
maxAuthors: 1
name: Recipes
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c2e9e108-babb-4c82-8ebb-38b86ba8e2e6: # Recipe Book
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry.twig
    uriFormat: 'recipes/{slug}'
type: channel
